name: publish-to-medium

on:
  push:
    branches:
      - main

jobs:
  publish-to-medium:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./posts/2023/01/12/testing123.md)"
      - uses: infraway/medium-post-markdown@v1.5.0
        with:
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          markdown_file: ${{ steps.post.outputs.data }}
          base_url: https://medium.com/nuggs
          post_url: https://medium.com/nuggs/posts
          post_status: draft
          post_license: all-rights-reserved